### ISSUE TITLE
Should be a GET

### ISSUE THREAD

**Issue by afeld** [jonahkagan/schematic-ipsum#1]
POST doesn't really make sense for retrieving the data, because you're not modifying or creating anything.

**Comment by jonahkagan** [comment]
I thought about this a lot, but I decided it would be simpler to use as a POST request. How would you suggest sending the JSON schema if it were a GET request? The only thing I can think of is to url-encode it and attach it as a query parameter. That seemed like it would just make things more difficult for anybody who wanted to quickly `curl` some data like so:

```
curl -X POST -H "Content-Type: application/json" --data @schema.json http://schematic-ipsum.herokuapp.com
```

Or using HTTPie:

```
http POST http://schematic-ipsum.herokuapp.com < schema.json
```

I don't think these tools support simply reading from a file and converting the contents to a query string.

If you think about it, in a way it's sort of like you are asking the server to create a new resource based on your schema (and then also send it back). Except it's non-deterministic and you can't ever request that resource again :grin:

**Comment by afeld** [comment]
Gotcha.  Since supporting both methods is trivial I'd probably just handle the encoded JSON query param, in case it makes someone's life easier (for some reason).

**Comment by jonahkagan** [comment]
I also just realized that the GET request currently loads the HTML page that describes the service, so I'd have to put the API at some other path if I wanted to support GET. I think I'll just wait and see if anybody needs the GET version, and if they request it, then I'll think about how to support it. Closing for now.
