### ISSUE TITLE
Support for enum

### ISSUE THREAD

**Issue by johnwimerirdeto** [jonahkagan/schematic-ipsum#4]
A feature to restrict values to a randomly chosen enum value would be nice.

E.g.
{
  "type" : "object",
  "properties" : {
    "direction" : {
      "type" : "string",
      "enum" : [ "North", "South", "East", "West" ]
    }
  }
}

Would generate:
{
    "direction": "North"
}

**Comment by jonahkagan** [comment]
Alright, I just added this in accordance with [sec 5.19](http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.19) of the spec. Thanks for the suggestion!
